remote_theme: pages-themes/cayman@v0.2.0
plugins:
- jekyll-remote-theme

title: Onzrod Documentation
description: Documentation for the Onzrod decentralized ride-sharing and delivery platform on TON Blockchain
show_downloads: true
google_analytics: # Add your Google Analytics tracking ID here

# Navigation
nav:
  - Home: /
  - Docs: /docs
  - API: /api
  - GitHub: https://github.com/ouiblock/onzrod

social_links:
  - GitHub: https://github.com/ouiblock/onzrod
  - Telegram: https://t.me/Oxmasteronchain
