remote_theme: pages-themes/cayman@v0.2.0
plugins:
- jekyll-remote-theme

title: TonMaps Documentation
description: Documentation for the decentralized ride-sharing and delivery platform on TON Blockchain
show_downloads: true
google_analytics: # Add your Google Analytics tracking ID here

# Navigation
nav:
  - User Guide: user-guide
  - Developer Guide: developer-guide
  - API Reference: api-reference
  - GitHub: https://github.com/ouiblock/Tonmaps
